management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9100
spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user-service: http://nacos-payment-provider